//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationTest3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class buy
    {
        public int id { get; set; }
        public int product_id { get; set; }
        public int supplier_id { get; set; }
        [Required]
        [DisplayFormat(DataFormatString = "{0:c}", ApplyFormatInEditMode = false)]
        [Display(Name = "仕入価格")]
        public decimal value { get; set; }
        [Required]
        [Display(Name = "入荷数")]
        public int qnt { get; set; }
        [Required]
        [Display(Name = "タイムスタンプ")]
        public System.DateTime date { get; set; }
    
        public virtual product product { get; set; }
        public virtual supplier supplier { get; set; }
    }
}
