//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationTest3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buy_View_1
    {
        public int id { get; set; }
        public decimal value { get; set; }
        public int qnt { get; set; }
        public byte[] date { get; set; }
        public string pcode { get; set; }
        public string name { get; set; }
        public int stok { get; set; }
        public string Expr1 { get; set; }
        public string Expr2 { get; set; }
    }
}
