//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationTest3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class maker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public maker()
        {
            this.product = new HashSet<product>();
        }
    
        public int id { get; set; }
        [Required]
        [Display(Name = "メーカー")]
        public string name { get; set; }
        
        [Display(Name = "住所１")]
        public string address1 { get; set; }
        
        [Display(Name = "電話番号")]
        public Nullable<int> TEL { get; set; }
        
        [Display(Name = "郵便番号")]
        public Nullable<int> PostNo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product> product { get; set; }
    }
}
