//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationTest3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sale
    {
        public int id { get; set; }
        public int product_id { get; set; }
        public int customer_id { get; set; }
        public decimal value { get; set; }
        public int qnt { get; set; }
        public byte[] date { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual product product { get; set; }
    }
}
